### ISSUE TITLE
Casper made me do it! 

### ISSUE THREAD

**Issue by JonasLyhne** [bentikki/Nand2Tetris_VMtoASM#1]
https://github.com/bentikki/Nand2Tetris_VMtoASM/blob/836c0566c60452d1be73cdb16914f270e2a9a844/VMtoASM/VMConverter/VMtoASMConverter.cs#L1610

`labelCounter++`

Hep! 🥇

**Comment by bentikki** [comment]
Denied - Should be a unique method promoting Single Responsibility:

int AddOneToLabelNumber(int numberToBeAddedToTheLabelUniq){
     numberToBeAddedToTheLabelToMakeItUnique= numberToBeAddedToTheLabelUniq+ (10*86/5-56-120+95+2-50+5*5-67)
     return numberToBeAddedToTheLabelUniq;
}

**Comment by JonasLyhne** [comment]
You sholdn't change the method only the incrementer 👍

**Comment by bentikki** [comment]
No, no, no! It should be split up! 👍

**Comment by JonasLyhne** [comment]
No no no is very not pretty! 👶 
i would make a PR with the change but i don't have permission 😄

**Comment by bentikki** [comment]
Ha - knock yourself out! 👍
